In [ ]:
my_list=[5,10,15,20,25,30]
print(my_list)

[5, 10, 15, 20, 25, 30]


In [ ]:
import numpy as np
array=np.array(my_list)
print(array)

[ 5 10 15 20 25 30]


In [ ]:
np.ones(3*3)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(7*3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [5]:

 import numpy as np
 n=np.random.randint(1,20,(4,5))
 n

array([[ 6, 12,  4, 13,  8],
       [ 2,  2, 17,  4,  3],
       [ 8, 16, 17, 17, 16],
       [ 4, 15,  1, 19,  5]])

In [19]:
import numpy as np
n=np.random. randint(1,50,(6,7))
n


array([[28, 21, 39, 36, 44, 21, 47],
       [49, 27, 21, 43, 45, 28, 35],
       [17, 46, 45, 48, 42, 10, 29],
       [ 3,  2, 48, 41, 15, 38, 22],
       [22, 22, 20,  4, 49, 21, 48],
       [ 4, 43, 38, 48, 26, 27,  6]])

In [27]:
import numpy as np
n=np.random.randint(1,50,(6,7))
n
n[4,2]

np.int64(1)

In [34]:
import numpy as np
n=np.arange(1,25).reshape(4,6)
n

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [35]:
import numpy as np
n=np.arange(1,25).reshape(4,6)
n[::-1]

array([[19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [36]:
import numpy as np
n=np.arange(1,25).reshape(4,6)
n[:,0]

array([ 1,  7, 13, 19])

In [41]:
import numpy as np
n=np.arange(1,25).reshape(4,6)
n[::2]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])